apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
      - name: production
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-00-1e7bd809bcb5/my-repository/sample-app:v1.0
        ports:
        - containerPort: 8080
